"""Generates the Hermit launcher icon and Android TV banner (python hermit/make_hermit_icon.py).

The same 16x16 pixel art as Hermit for Windows (hermit crab carrying the Shell seashell, front view):
- main/res/drawable/hermit_launcher_foreground.xml: adaptive icon foreground, one path per colour,
  pixels kept square; also the Android TV channel logo (drawable/ic_channel.xml);
- main/res/mipmap-anydpi-v26/ic_launcher.xml: the adaptive icon with a transparent background, so
  launchers that honour it show the crab without a plate;
- main/res/mipmap-*dpi/ic_launcher.png: the icon for Android 7.x and older;
- main/res/drawable-xhdpi/atv_banner.png: the 320x180 Android TV launcher banner.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pixelart as px

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'app', 'src'))

HERMIT = px.parse("""
....KKKKKKKK....
..KKSSTTTTTtKK..
.KSSTTKKKKTTttK.
.KSTTKTTTTKTttK.
KSTTKTKKKTKTtttK
KTTTKTKSKTKTtttK
KTTTTKTTTKTTtttK
.KKKKKKKKKKKKKK.
KK..KwK..KwK..KK
KRK.KKK..KKK.KRK
KRRK.K....K.KRRK
.KRRKRRRRRRKRRK.
..KRRRRRRRRRRK..
..KRrRRRRRRrRK..
.K.KKKKKKKKKK.K.
.K..K......K..K.
""")

# 16 pixels of 3.5dp = 56dp, centred in the 108dp canvas: inside the 72dp area every launcher
# mask keeps, with the corners clear of a circular mask.
CELL = 3.5
OFFSET = (108 - 16 * CELL) / 2


def foreground():
    paths = {}
    for ch, x, y, n in px.runs(HERMIT):
        paths.setdefault(ch, []).append('M%d,%dh%dv1h-%dz' % (x, y, n, n))
    body = ''.join('        <path android:fillColor="#%02X%02X%02X" android:pathData="%s"/>\n'
                   % (*px.PALETTE[ch], ''.join(d)) for ch, d in paths.items())
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Hermit: pixel-art hermit crab carrying the Shell seashell (generated by\n'
            '     hermit/make_hermit_icon.py; same artwork as Hermit for Windows). -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
            '    <group\n        android:scaleX="%g"\n        android:scaleY="%g"\n'
            '        android:translateX="%g"\n        android:translateY="%g">\n%s    </group>\n</vector>\n'
            % (CELL, CELL, OFFSET, OFFSET, body))


ADAPTIVE = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Hermit launcher icon (generated by hermit/make_hermit_icon.py): pixel art on a transparent
     background. Launchers that put icons on their own plate (e.g. One UI icon frames) add one. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@android:color/transparent"/>
    <foreground android:drawable="@drawable/hermit_launcher_foreground"/>
</adaptive-icon>
'''

# 5x7 pixel letters for the TV banner ('X' is ink)
LETTERS = {
    'H': ['X...X', 'X...X', 'X...X', 'XXXXX', 'X...X', 'X...X', 'X...X'],
    'E': ['XXXXX', 'X....', 'X....', 'XXXX.', 'X....', 'X....', 'XXXXX'],
    'R': ['XXXX.', 'X...X', 'X...X', 'XXXX.', 'X.X..', 'X..X.', 'X...X'],
    'M': ['X...X', 'XX.XX', 'X.X.X', 'X.X.X', 'X...X', 'X...X', 'X...X'],
    'I': ['XXX', '.X.', '.X.', '.X.', '.X.', '.X.', 'XXX'],
    'T': ['XXXXX', '..X..', '..X..', '..X..', '..X..', '..X..', '..X..'],
}

BACKGROUND = (0x16, 0x16, 0x16)    # hermit_background
TEXT = (0xF4, 0xF4, 0xF4)          # hermit_text_primary
ACCENT = (0x08, 0xBD, 0xBA)        # hermit_accent


def word(text):
    rows = [''] * 7
    for i, ch in enumerate(text):
        for r in range(7):
            rows[r] += ('.' if i else '') + LETTERS[ch][r]
    return rows


def banner(width=320, height=180):
    """The crab and the name in pixel letters, centred, with a teal rule under the name."""
    crab_scale, text_scale, gap = 6, 5, 24
    name = word('HERMIT')
    crab_w = 16 * crab_scale
    text_w = len(name[0]) * text_scale
    text_h = 7 * text_scale
    left = (width - (crab_w + gap + text_w)) // 2
    text_x = left + crab_w + gap
    text_y = (height - text_h) // 2 - 4
    return px.canvas_png(width, height, BACKGROUND, [
        (HERMIT, left, (height - crab_w) // 2, crab_scale, px.PALETTE),
        (name, text_x, text_y, text_scale, {'X': TEXT}),
        (['X' * text_w] * 4, text_x, text_y + text_h + 10, 1, {'X': ACCENT}),
    ])


with open('main/res/drawable/hermit_launcher_foreground.xml', 'w', encoding='utf-8', newline='\n') as f:
    f.write(foreground())
with open('main/res/mipmap-anydpi-v26/ic_launcher.xml', 'w', encoding='utf-8', newline='\n') as f:
    f.write(ADAPTIVE)
for density, size in (('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)):
    d = 'main/res/mipmap-%s' % density
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, 'ic_launcher.png'), 'wb') as f:
        f.write(px.png(HERMIT, size))
with open('main/res/drawable-xhdpi/atv_banner.png', 'wb') as f:
    f.write(banner())
print('ok')
