"""Generates Hermit's Android string resources (python hermit/make_hermit_strings.py).

- nonRoot/res/values{,-ko}/strings.xml: Hermit / Shell wording for base strings and translations the
  base strings lack (the nonRoot flavor source set wins over main).
- main/res/values{,-ko}/hermit_strings.xml: strings for Hermit's own features.
"""
import os
import re

# Run from anywhere: paths are relative to app/src of this repository.
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'app', 'src'))


def write(path, text, crlf=False):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    text = text.replace('\r\n', '\n')
    if crlf:
        text = text.replace('\n', '\r\n')
    open(path, 'w', encoding='utf-8', newline='').write(text)
X = '<?xml version="1.0" encoding="utf-8"?>\n'


def esc(text):
    # Android string escaping: apostrophes and double quotes, leading @/? handled by callers.
    return (text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            .replace("'", "\\'").replace('"', '\\"'))


def res(header, pairs, arrays=()):
    out = [X + '<!-- ' + header + ' -->', '<resources>']
    for name, text, *fmt in pairs:
        attr = ' formatted="false"' if fmt and fmt[0] == 'nofmt' else ''
        out.append('    <string name="%s"%s>%s</string>' % (name, attr, esc(text)))
    for name, items in arrays:
        out.append('    <string-array name="%s" translatable="false">' % name)
        out += ['        <item>%s</item>' % esc(i) for i in items]
        out.append('    </string-array>')
    out.append('</resources>')
    return '\n'.join(out) + '\n'


# ---- Upstream overrides ------------------------------------------------------------------
over_en = [
    ('message_decoding_error', 'Hermit has crashed due to an incompatibility with this device\'s video decoder. Try adjusting the streaming settings if the crashes continue.'),
    ('summary_seekbar_deadzone', 'Note: Some games can enforce a larger deadzone than what Hermit is configured to use.'),
    ('summary_checkbox_usb_bind_all', 'Use Hermit\'s USB driver for all supported gamepads, even if native Xbox controller support is present'),
    ('summary_language_list', 'Language to use for Hermit'),
    ('local_network_rationale', 'Hermit requires local network permissions to communicate with nearby hosts'),
    ('searching_pc', 'Looking for host PCs on your local network…\\n\\nMake sure the streaming host (such as Shell) is running on your PC.'),
    ('pair_pairing_help', 'Enter this PIN on your host\'s pairing page (in Shell: web UI → Pairing).'),
    ('ip_hint', 'IP address or host name (e.g. 192.168.0.10)'),
    ('error_404', 'The host returned an HTTP 404 error. Make sure your PC has a supported GPU. Remote desktop software can also cause this error. Try restarting your PC or reinstalling the host software.'),
    ('summary_checkbox_enable_sops', 'Allow the host to change game settings for the best streaming'),
    ('summary_checkbox_touchscreen_trackpad', 'On: the touchscreen moves the pointer like a trackpad. Off: you touch the host screen directly (tap to click, drag to scroll, long press then drag to select or move, two-finger tap for a right click).'),
]
over_ko = [
    ('message_decoding_error', '이 기기의 영상 디코더와 호환되지 않아 Hermit이 종료되었습니다. 계속 종료되면 스트리밍 설정을 바꿔 보세요.'),
    ('text_native_res_dialog', '네이티브 해상도나 FPS는 스트리밍 서버가 지원하지 않을 수 있습니다. 호스트 PC에 맞는 사용자 지정 디스플레이 모드를 직접 설정해야 할 수 있습니다.\\n\\nNVIDIA 제어판에서 화면에 맞는 사용자 지정 해상도를 만들 경우, 모니터 손상이나 PC 불안정 등 잠재적인 문제에 대한 NVIDIA의 경고를 읽고 이해했는지 확인하세요.\\n\\nHermit은 PC에서 사용자 지정 해상도를 만들어 생기는 문제에 책임지지 않습니다.\\n\\n모니터가 필요한 디스플레이 구성을 지원하지 않으면 가상 모니터를 설정해 볼 수 있습니다. 기기나 호스트 PC가 특정 해상도나 주사율의 스트리밍을 지원하지 않을 수도 있습니다.'),
    ('summary_checkbox_usb_bind_all', 'Xbox 컨트롤러를 기본 지원하는 경우에도 지원되는 모든 게임패드에 Hermit의 USB 드라이버를 사용합니다'),
    ('summary_language_list', 'Hermit에서 사용할 언어를 선택합니다'),
    ('local_network_rationale', '가까운 호스트와 통신하려면 Hermit에 로컬 네트워크 권한이 필요합니다'),
    ('title_show_guide_button', '가이드 버튼 표시'),
    ('summary_show_guide_button', '화면에 가이드 버튼을 표시합니다'),
    ('searching_pc', '로컬 네트워크에서 호스트 PC를 찾는 중…\\n\\nPC에서 스트리밍 호스트(Shell 등)가 실행 중인지 확인하세요.'),
    ('pair_pairing_help', '호스트의 페어링 페이지에 이 PIN을 입력하세요 (Shell: 웹 UI → 페어링).'),
    ('error_404', '호스트가 HTTP 404 오류를 반환했습니다. PC의 GPU가 지원되는지 확인하세요. 원격 데스크톱 프로그램도 이 오류를 일으킬 수 있습니다. PC를 다시 시작하거나 호스트 프로그램을 다시 설치해 보세요.'),
    ('summary_checkbox_enable_sops', '최적의 스트리밍을 위해 호스트가 게임 설정을 바꾸도록 허용합니다'),

    # PC list, pairing, Wake-on-LAN ("PC" rather than the Korean word for "computer")
    ('pcview_menu_send_wol', 'PC 깨우기 (Wake-on-LAN)'),
    ('wol_waking_msg', 'PC를 켜는 중입니다. 켜지지 않으면 PC의 BIOS와 네트워크 어댑터에서 Wake-on-LAN이 켜져 있는지 확인하세요.'),
    ('wol_fail', 'Wake-on-LAN 패킷을 보내지 못했습니다'),
    ('wol_pc_online', 'PC가 이미 켜져 있습니다'),
    ('error_manager_not_running', '앱 준비가 아직 끝나지 않았습니다. 잠시 후 다시 시도하세요.'),
    ('pair_pc_offline', 'PC가 오프라인 상태입니다'),
    ('error_pc_offline', 'PC가 오프라인 상태입니다'),
    ('pair_pc_ingame', 'PC에서 아직 앱이 실행 중입니다. 페어링하기 전에 앱을 종료하세요.'),
    ('pcview_menu_app_list', '모든 앱 보기'),
    ('title_add_pc', 'PC 직접 추가'),
    ('ip_hint', 'IP 주소 또는 호스트 이름 (예: 192.168.0.10)'),
    ('addpc_fail', 'PC에 연결하지 못했습니다. PC의 방화벽과 포트 설정을 확인하세요.'),
    ('addpc_success', 'PC를 추가했습니다'),

    # App list: apps, not games or sessions
    ('applist_menu_resume', '이어서 하기'),
    ('applist_menu_quit', '앱 종료'),
    ('applist_menu_quit_and_start', '현재 앱 종료 후 시작'),
    ('applist_menu_hide_app', '앱 숨기기'),
    ('applist_quit_confirmation', '실행 중인 앱을 종료할까요? 저장하지 않은 작업은 사라집니다.'),
    ('summary_checkbox_small_icon_mode', '한 화면에 더 많은 앱이 보이도록 아이콘을 작게 표시합니다'),
    ('summary_checkbox_host_audio', '이 기기와 PC에서 모두 소리를 재생합니다'),

    # Same terms as the stream panel
    ('title_resolution_list', '해상도'),
    ('title_fps_list', '프레임 레이트(FPS)'),
    ('title_seekbar_bitrate', '비트레이트'),
    ('title_video_format', '비디오 코덱'),
    ('videoformat_auto', '자동 (권장)'),
    ('videoformat_h264always', 'H.264'),
    ('videoformat_hevcalways', 'HEVC (H.265)'),
    ('videoformat_av1always', 'AV1 (실험적)'),
    ('title_enable_perf_overlay', '성능 오버레이'),
    ('summary_enable_perf_overlay', '스트리밍 중 실시간 성능 정보를 화면에 표시합니다'),
    ('title_checkbox_touchscreen_trackpad', '터치스크린을 트랙패드로 사용'),
    ('summary_checkbox_touchscreen_trackpad', '켜면 터치스크린이 트랙패드처럼 커서를 움직입니다. 끄면 PC 화면을 직접 터치합니다(탭은 클릭, 끌면 스크롤, 길게 누른 뒤 끌면 선택·이동, 두 손가락 탭은 우클릭).'),
    ('category_on_screen_controls_settings', '화면 컨트롤러'),
    ('title_checkbox_show_onscreen_controls', '화면 컨트롤러 표시'),
    ('summary_checkbox_show_onscreen_controls', '화면에 게임패드 버튼을 표시합니다'),
    ('dialog_title_osc_opacity', '화면 컨트롤러 불투명도'),
    ('title_osc_opacity', '화면 컨트롤러 불투명도'),
    ('summary_osc_opacity', '화면 컨트롤러 버튼의 불투명도입니다. 100이면 완전히 불투명합니다.'),
    ('title_reset_osc', '화면 컨트롤러 배치 초기화'),
    ('dialog_title_reset_osc', '화면 컨트롤러 배치 초기화'),
    ('summary_reset_osc', '화면 컨트롤러 버튼을 기본 크기와 위치로 되돌립니다'),
    ('dialog_text_reset_osc', '저장된 화면 컨트롤러 배치를 초기화할까요?'),
    ('toast_reset_osc_success', '화면 컨트롤러 배치를 초기화했습니다'),
    ('summary_checkbox_vibrate_osc', '화면 컨트롤러를 쓰는 동안 게임패드 진동을 기기 진동으로 재현합니다'),
    ('summary_checkbox_flip_face_buttons', '컨트롤러와 화면 컨트롤러의 A/B, X/Y 버튼을 서로 바꿉니다'),
    ('summary_only_l3r3', 'L3와 R3를 뺀 화면 컨트롤러 버튼을 모두 숨깁니다'),

    # Typos and spacing
    ('audioconf_stereo', '스테레오'),
    ('summary_seekbar_deadzone', '참고: 일부 게임은 이 설정보다 큰 데드존이 적용되어 있을 수 있습니다.'),
    ('title_checkbox_disable_warnings', '경고 메시지 끄기'),
    ('summary_checkbox_disable_warnings', '스트리밍 중 화면에 연결 경고 메시지를 표시하지 않습니다'),
    ('summary_checkbox_xb1_driver', 'Xbox 컨트롤러를 기본 지원하지 않는 기기에서 내장 USB 드라이버를 사용합니다'),
    ('title_checkbox_enable_pip', 'PIP 모드 사용'),
    ('summary_checkbox_enable_pip', 'PIP 모드에서는 화면을 볼 수만 있고 조작할 수는 없습니다'),
    ('title_enable_hdr', 'HDR 사용 (실험적)'),
]

arrays_src = open('main/res/values/arrays.xml', encoding='utf-8').read()
m = re.search(r'<string-array name="language_names"[^>]*>(.*?)</string-array>', arrays_src, re.S)
names = re.findall(r'<item>(.*?)</item>', m.group(1))
assert names[0] == 'Default', names[0]
names_hermit = ['@string/hermit_language_default'] + names[1:]

write('nonRoot/res/values/strings.xml',
      res('Hermit: base strings reworded for Hermit / Shell.', over_en,
          arrays=[('language_names', names_hermit)]), crlf=True)
write('nonRoot/res/values-ko/strings.xml',
      res('Hermit: Korean wording and translations that the base strings lack.',
          over_ko), crlf=True)

# ---- Hermit strings -----------------------------------------------------------------------
# (name, English, Korean[, 'nofmt'])
hermit = [
    # Upstream messages that were hard-coded in English
    ('hermit_hdr_display_unsupported', 'Display does not support HDR10', '이 화면은 HDR10을 지원하지 않습니다'),
    ('hermit_hdr_requires_android7', 'HDR requires Android 7.0 or later', 'HDR은 Android 7.0 이상에서만 쓸 수 있습니다'),
    ('hermit_hdr_decoder_unsupported', 'Decoder does not support HDR10 profile', '디코더가 HDR10 프로필을 지원하지 않습니다'),
    ('hermit_hevc_decoder_missing', 'No HEVC decoder found', 'HEVC 디코더를 찾지 못했습니다'),
    ('hermit_av1_decoder_missing', 'No AV1 decoder found', 'AV1 디코더를 찾지 못했습니다'),
    ('hermit_h264_unsupported', 'This device or ROM doesn\'t support hardware accelerated H.264 playback.', '이 기기(또는 ROM)는 H.264 하드웨어 가속 재생을 지원하지 않습니다.'),
    ('hermit_mouse_emulation_on', 'Mouse emulation: on', '마우스 에뮬레이션 켜짐'),
    ('hermit_mouse_emulation_off', 'Mouse emulation: off', '마우스 에뮬레이션 꺼짐'),
    ('hermit_osc_config_title', 'Configuration', '화면 컨트롤러 설정'),
    ('hermit_osc_edit_move', 'Editing the on-screen controls: move buttons', '화면 컨트롤러 편집: 버튼 이동'),
    ('hermit_osc_edit_resize', 'Editing the on-screen controls: resize buttons', '화면 컨트롤러 편집: 버튼 크기 조절'),
    ('hermit_osc_edit_done', 'Finished editing the on-screen controls', '화면 컨트롤러 편집을 마쳤습니다'),
    ('hermit_osc_config_move', 'Move', '이동'),
    ('hermit_osc_config_resize', 'Resize', '크기 조절'),
    ('hermit_osc_config_cancel', 'Cancel', '취소'),
    ('hermit_quit_not_owner', 'This session wasn\'t started by this device, so it cannot be quit. End streaming on the original device or the PC itself. (Error code: %1$d)',
     '이 세션은 다른 기기에서 시작해서 여기서 종료할 수 없습니다. 시작한 기기나 PC에서 종료하세요. (오류 코드: %1$d)'),
    ('hermit_shortcut_app_removed', 'App removed from PC', 'PC에서 삭제된 앱입니다'),
    ('hermit_language_default', 'Default', '기본값 (시스템 언어)'),
    ('hermit_label_stream_settings', 'Streaming settings', '스트리밍 설정'),
    ('hermit_label_add_computer', 'Add PC manually', 'PC 직접 추가'),
    ('hermit_add_pc_button', 'Add', '추가'),
    ('hermit_action_cancel', 'Cancel', '취소'),
    ('hermit_action_delete', 'Delete', '삭제'),
    ('hermit_action_quit_app', 'Quit app', '앱 종료'),
    ('hermit_pair_cancelled', 'Pairing cancelled', '페어링을 취소했습니다'),
    ('hermit_shield_hdr_firmware', 'Update the firmware on your NVIDIA SHIELD Android TV to enable HDR', 'HDR을 쓰려면 NVIDIA SHIELD Android TV 펌웨어를 업데이트하세요'),

    # Upstream connection messages (NvConnection) that were hard-coded in English
    ('hermit_conn_version_malformed', 'Server version malformed', '서버 버전 정보가 올바르지 않습니다'),
    ('hermit_conn_not_paired', 'Device not paired with computer', '이 기기는 PC와 페어링되어 있지 않습니다'),
    ('hermit_conn_no_hdr', 'Your PC GPU does not support streaming HDR. The stream will be SDR.', 'PC의 GPU가 HDR 스트리밍을 지원하지 않아 SDR로 스트리밍합니다.'),
    ('hermit_conn_host_no_above_4k', 'Your host PC does not support streaming at resolutions above 4K.', '호스트 PC가 4K를 넘는 해상도의 스트리밍을 지원하지 않습니다.'),
    ('hermit_conn_device_needs_hevc_above_4k', 'Your streaming device must support HEVC or AV1 to stream at resolutions above 4K.', '4K를 넘는 해상도로 스트리밍하려면 이 기기가 HEVC나 AV1을 지원해야 합니다.'),
    ('hermit_conn_update_host_4k', 'You must update the host software to stream in 4K. The stream will be 1080p.', '4K로 스트리밍하려면 호스트 소프트웨어를 업데이트해야 합니다. 1080p로 스트리밍합니다.'),
    ('hermit_conn_app_not_found', "The app %1$s is not in the host's app list", '호스트의 앱 목록에 %1$s 앱이 없습니다'),
    ('hermit_conn_resume_failed', 'Failed to resume existing session', '기존 세션을 이어가지 못했습니다'),
    ('hermit_conn_resume_not_owner', "This session wasn't started by this device, so it cannot be resumed. End streaming on the original device or the PC itself and try again. (Error code: %1$d)",
     '이 세션은 다른 기기에서 시작해서 여기서 이어갈 수 없습니다. 시작한 기기나 PC에서 종료한 뒤 다시 시도하세요. (오류 코드: %1$d)'),
    ('hermit_conn_app_minimized', 'The application is minimized. Resume it on the PC manually or quit the session and start streaming again.', '앱이 최소화되어 있습니다. PC에서 직접 앱을 다시 띄우거나 세션을 종료한 뒤 다시 스트리밍하세요.'),
    ('hermit_conn_quit_failed', 'Failed to quit previous session! You must quit it manually', '이전 세션을 종료하지 못했습니다. 직접 종료해야 합니다.'),
    ('hermit_conn_launch_failed', 'Failed to launch application', '앱을 실행하지 못했습니다'),
    ('hermit_conn_stage_starting', 'Starting %1$s…', '%1$s 시작하는 중…'),
    ('hermit_conn_stage_failed', 'Could not connect at %1$s (error %2$d)', '%1$s 단계에서 연결하지 못했습니다 (오류 %2$d)'),
    ('hermit_conn_app_failed', 'Could not start %1$s (error %2$d)', '%1$s 앱을 시작하지 못했습니다 (오류 %2$d)'),
    # Connection stages by number (core library Connection.c stageNames)
    ('hermit_stage_platform_init', 'platform initialization', '플랫폼 초기화'),
    ('hermit_stage_name_resolution', 'name resolution', '이름 확인'),
    ('hermit_stage_audio_init', 'audio stream initialization', '오디오 스트림 준비'),
    ('hermit_stage_rtsp', 'RTSP handshake', 'RTSP 연결'),
    ('hermit_stage_control_init', 'control stream initialization', '제어 스트림 준비'),
    ('hermit_stage_video_init', 'video stream initialization', '비디오 스트림 준비'),
    ('hermit_stage_input_init', 'input stream initialization', '입력 스트림 준비'),
    ('hermit_stage_control_start', 'control stream establishment', '제어 스트림 연결'),
    ('hermit_stage_video_start', 'video stream establishment', '비디오 스트림 연결'),
    ('hermit_stage_audio_start', 'audio stream establishment', '오디오 스트림 연결'),
    ('hermit_stage_input_start', 'input stream establishment', '입력 스트림 연결'),

    # Host errors shown instead of the raw exception text
    ('hermit_host_error', 'Host error: %1$s (error code %2$d)', '호스트 오류: %1$s (오류 코드 %2$d)'),
    ('hermit_host_error_audio', "The host found no audio capture device. Check the host PC's audio devices and the host software installation.",
     '호스트에서 오디오 캡처 장치를 찾지 못했습니다. 호스트 PC의 오디오 장치와 호스트 프로그램 설치를 확인하세요.'),
    ('hermit_host_unreachable', 'Could not connect to the host. Check the network and the PC.', '호스트에 연결하지 못했습니다. 네트워크와 PC 상태를 확인하세요.'),
    ('hermit_host_bad_response', 'The response of the host could not be read.', '호스트의 응답을 읽지 못했습니다.'),

    # Quitting the app on the host
    ('hermit_quit_confirm_title', 'Quit the app?', '앱을 종료할까요?'),
    ('hermit_quit_confirm_message', 'Quits %1$s running on the host. Unsaved work will be lost.', '호스트에서 실행 중인 %1$s 앱을 종료합니다. 저장하지 않은 작업은 사라집니다.'),
    ('hermit_quit_confirm_message_any', 'Quits the app running on the host. Unsaved work will be lost.', '호스트에서 실행 중인 앱을 종료합니다. 저장하지 않은 작업은 사라집니다.'),
    ('hermit_quit_in_progress', 'Quitting %1$s…', '%1$s 앱을 종료하는 중…'),
    ('hermit_quit_done', 'Quit %1$s', '%1$s 앱을 종료했습니다'),
    ('hermit_quit_failed', 'Could not quit %1$s', '%1$s 앱을 종료하지 못했습니다'),
    ('hermit_quit_in_progress_any', 'Quitting the running app…', '실행 중인 앱을 종료하는 중…'),
    ('hermit_quit_done_any', 'Quit the running app', '실행 중인 앱을 종료했습니다'),
    ('hermit_quit_failed_any', 'Could not quit the running app', '실행 중인 앱을 종료하지 못했습니다'),

    # PC and app details
    ('hermit_details_name', 'Name', '이름'),
    ('hermit_details_state', 'State', '상태'),
    ('hermit_details_online', 'Online', '온라인'),
    ('hermit_details_offline', 'Offline', '오프라인'),
    ('hermit_details_checking', 'Checking', '확인 중'),
    ('hermit_details_active_address', 'Current address', '현재 주소'),
    ('hermit_details_local_address', 'Local address', '로컬 주소'),
    ('hermit_details_remote_address', 'Remote address', '원격 주소'),
    ('hermit_details_ipv6_address', 'IPv6 address', 'IPv6 주소'),
    ('hermit_details_manual_address', 'Manual address', '수동 주소'),
    ('hermit_details_mac_address', 'MAC address', 'MAC 주소'),
    ('hermit_details_pairing', 'Pairing', '페어링'),
    ('hermit_details_paired', 'Paired', '됨'),
    ('hermit_details_not_paired', 'Not paired', '안 됨'),
    ('hermit_details_running_app', 'Running app ID', '실행 중인 앱 ID'),
    ('hermit_details_https_port', 'HTTPS port', 'HTTPS 포트'),
    ('hermit_details_hdr', 'HDR support', 'HDR 지원'),
    ('hermit_details_yes', 'Yes', '예'),
    ('hermit_details_unknown', 'Unknown', '알 수 없음'),
    ('hermit_details_id', 'ID', 'ID'),
    ('hermit_conn_other_app_running', 'A different app is now running on the host, so the stream was not reconnected.', '호스트에서 다른 앱이 실행 중이라 다시 연결하지 않았습니다.'),

    # Stream panel
    ('hermit_panel_title', 'Stream settings', '스트림 설정'),
    ('hermit_panel_handle', 'Stream settings', '스트림 설정'),
    ('title_hermit_panel_handle_side', 'Stream settings handle', '스트림 설정 손잡이 위치'),
    ('hermit_panel_handle_right', 'Right edge', '오른쪽 가장자리'),
    ('hermit_panel_handle_left', 'Left edge', '왼쪽 가장자리'),
    ('hermit_panel_handle_move_hint', 'Tap the handle to open this panel; press and hold it, then drag, to move it up or down.',
     '손잡이를 누르면 이 패널이 열립니다. 꾹 누른 채 끌면 위아래로 옮길 수 있습니다.'),
    ('hermit_panel_close', 'Back to the stream', '스트림으로 돌아가기'),
    ('hermit_panel_section_picture', 'PICTURE AND QUALITY', '화면과 화질'),
    ('hermit_panel_reconnect_note', 'Applied by reconnecting: the picture pauses for 2 to 3 seconds and the host app keeps running.',
     '다시 연결해 적용합니다. 화면이 2~3초 멈추고, 호스트의 앱은 계속 실행됩니다.'),
    ('hermit_panel_resolution', 'Resolution', '해상도'),
    ('hermit_panel_resolution_hint', 'Other size: width x height, e.g. %1$s', '직접 입력: 가로x세로 (예: %1$s)'),
    ('hermit_panel_resolution_error', 'Enter width x height (320x240 to 7680x4320)', '가로x세로로 입력하세요 (320x240~7680x4320)'),
    ('hermit_panel_bitrate_error', 'Enter 0.5 to 150 Mbps', '0.5~150 Mbps 사이로 입력하세요'),
    ('hermit_panel_fps', 'Frame rate (FPS)', '프레임 레이트(FPS)'),
    ('hermit_panel_bitrate', 'Bitrate', '비트레이트'),
    ('hermit_panel_bitrate_applying', 'Applying the bitrate…', '비트레이트를 적용하는 중…'),
    ('hermit_panel_bitrate_live', 'The bitrate is applied at once, without reconnecting.', '비트레이트는 다시 연결하지 않고 바로 적용됩니다.'),
    ('hermit_panel_bitrate_reconnect', 'This host cannot change the bitrate during a stream; it is applied by reconnecting.',
     '이 호스트는 스트리밍 중에 비트레이트를 바꿀 수 없어 다시 연결해 적용합니다.'),
    ('hermit_panel_bitrate_failed', 'The bitrate change could not be confirmed; apply it by reconnecting, or move the slider to send it again.',
     '비트레이트 변경을 확인하지 못했습니다. 다시 연결해 적용하거나 슬라이더를 다시 움직여 보내세요.'),
    ('hermit_panel_auto_bitrate', 'Adjust automatically to the network', '네트워크에 맞춰 자동 조절'),
    ('hermit_panel_auto_bitrate_failed', 'The last change could not be confirmed; trying again.', '마지막 변경을 확인하지 못해 다시 시도하는 중입니다.'),
    ('hermit_bitrate_failed_toast', 'The bitrate change could not be confirmed. See the stream settings.', '비트레이트 변경을 확인하지 못했습니다. 스트림 설정에서 확인하세요.'),
    ('hermit_bitrate_reconnect_toast', 'This host cannot change the bitrate during a stream. Apply it from the stream settings (reconnects).', '이 호스트는 스트리밍 중에 비트레이트를 바꿀 수 없습니다. 스트림 설정에서 적용하세요(다시 연결).'),
    ('hermit_panel_auto_bitrate_status', 'Automatic: now %1$s Mbps (up to %2$s Mbps)', '자동 조절: 지금 %1$s Mbps (최대 %2$s Mbps)'),
    ('title_checkbox_hermit_auto_bitrate', 'Adjust the bitrate automatically (Shell host)', '비트레이트 자동 조절 (Shell 호스트)'),
    ('summary_checkbox_hermit_auto_bitrate', 'While streaming, lowers the bitrate when frames are lost or the round trip rises, and raises it again up to the bitrate above when the network is calm, without reconnecting.',
     '스트리밍 중 프레임 손실이나 왕복 지연이 늘면 비트레이트를 낮추고, 네트워크가 안정되면 위에서 고른 비트레이트까지 다시 올립니다. 다시 연결하지 않습니다.'),
    ('hermit_panel_codec', 'Video codec', '비디오 코덱'),
    ('hermit_panel_hdr', 'HDR', 'HDR'),
    ('hermit_panel_apply', 'Apply and reconnect', '적용하고 다시 연결'),
    ('hermit_panel_revert', 'Revert', '되돌리기'),
    ('hermit_panel_section_display', 'DISPLAY', '표시'),
    ('hermit_panel_live_note', 'Applied at once.', '바로 적용됩니다.'),
    ('hermit_panel_overlay', 'Performance overlay', '성능 오버레이'),
    ('hermit_panel_section_input', 'INPUT', '입력'),
    ('hermit_panel_section_other', 'OTHER', '기타'),
    ('hermit_panel_trackpad', 'Use the touchscreen as a trackpad', '터치스크린을 트랙패드로 사용'),
    ('hermit_panel_osc', 'Show on-screen controls', '화면 컨트롤러 표시'),
    ('hermit_panel_disconnect', 'Disconnect', '연결 끊기'),
    ('hermit_panel_quit_app', 'Quit app and disconnect', '앱 종료 후 끊기'),
    ('hermit_panel_back_hint', 'The back gesture opens and closes this panel.', '뒤로 가기로 이 패널을 열고 닫습니다.'),

    # Text input bar
    ('hermit_text_input_hint', 'Text to type on the host', 'PC에 입력할 텍스트'),
    ('hermit_text_input_send', 'Send', '보내기'),
    ('hermit_text_input_backspace', 'Backspace (in the field, or on the host when it is empty)', '백스페이스 (입력창에서, 비어 있으면 PC에서)'),
    ('hermit_text_input_enter', 'Send, then Enter', '보내고 Enter'),
    ('hermit_text_input_close', 'Close the text input', '텍스트 입력 닫기'),
    ('hermit_text_input_raw_keyboard', 'Phone keyboard straight to the host (arrows, Esc, game keys)', '폰 키보드로 PC에 바로 입력 (방향키, Esc, 게임 키)'),
    ('hermit_panel_text_input', 'Type text…', '텍스트 입력…'),
    ('hermit_keyboard_button', 'Type text on the host', 'PC에 텍스트 입력'),
    # Shortcut row of the text input bar (the buttons show the key names)
    ('hermit_key_shift_enter', 'Shift+Enter (a new line without sending, in chat apps)', 'Shift+Enter (채팅 앱에서 보내지 않고 줄 바꿈)'),
    ('hermit_key_left', 'Left arrow', '왼쪽 방향키'),
    ('hermit_key_up', 'Up arrow', '위쪽 방향키'),
    ('hermit_key_down', 'Down arrow', '아래쪽 방향키'),
    ('hermit_key_right', 'Right arrow', '오른쪽 방향키'),
    ('hermit_key_delete', 'Delete', 'Delete (커서 뒤 글자 지우기)'),
    ('hermit_key_select_all', 'Ctrl+A (select all)', 'Ctrl+A (모두 선택)'),
    ('hermit_key_copy', 'Ctrl+C (copy)', 'Ctrl+C (복사)'),
    ('hermit_key_cut', 'Ctrl+X (cut)', 'Ctrl+X (잘라내기)'),
    ('hermit_key_paste', 'Ctrl+V (paste)', 'Ctrl+V (붙여넣기)'),
    ('hermit_key_undo', 'Ctrl+Z (undo)', 'Ctrl+Z (실행 취소)'),
    ('hermit_key_alt_tab', 'Alt+Tab (the previous window)', 'Alt+Tab (이전 창으로 전환)'),
    ('hermit_key_win', 'Windows key (Start menu)', 'Windows 키 (시작 메뉴)'),
    ('hermit_key_task_manager', 'Ctrl+Shift+Esc (Task Manager)', 'Ctrl+Shift+Esc (작업 관리자)'),
    ('hermit_key_ctrl_alt_del', 'Ctrl+Alt+Del (lock, sign out, Task Manager)', 'Ctrl+Alt+Del (잠금, 로그아웃, 작업 관리자)'),

    # Quick menu (a button of the virtual keypad)
    ('hermit_quick_menu', 'Quick menu', '빠른 메뉴'),
    ('hermit_quick_touch', 'Touch', '터치 방식'),
    ('hermit_quick_touch_direct', 'Direct touch', '직접 터치'),
    ('hermit_quick_touch_trackpad', 'Trackpad', '트랙패드'),
    ('hermit_quick_quality', 'Quality (bitrate)', '화질 (비트레이트)'),
    ('hermit_quick_quality_high', 'High', '높음'),
    ('hermit_quick_quality_medium', 'Medium', '중간'),
    ('hermit_quick_quality_low', 'Low', '낮음'),
    ('hermit_quick_quality_note', 'Medium is the recommended bitrate for this stream. Applied at once; with automatic bitrate on, it is the maximum.',
     '중간은 이 스트림의 권장 비트레이트입니다. 바로 적용되며, 자동 비트레이트가 켜져 있으면 최대값이 됩니다.'),
    ('hermit_quick_orientation', 'Screen orientation', '화면 방향'),
    ('hermit_quick_keypad_edit', 'Edit the keypad', '가상 패드 편집'),
    ('hermit_quick_text_input', 'Type text', '텍스트 입력'),
    ('hermit_quick_overlay_show', 'Show performance', '성능 표시 켜기'),
    ('hermit_quick_overlay_hide', 'Hide performance', '성능 표시 끄기'),
    ('hermit_quick_settings', 'All stream settings', '스트림 설정 전체'),

    # Screen orientation of the stream
    ('hermit_orientation_auto', 'Auto', '자동'),
    ('hermit_orientation_landscape', 'Landscape', '가로'),
    ('hermit_orientation_portrait', 'Portrait', '세로'),
    ('hermit_orientation_osc_note', 'The screen stays in landscape while the on-screen controls are shown.', '화면 컨트롤러를 표시하는 동안은 가로로 유지됩니다.'),
    ('hermit_panel_orientation_hint', 'Auto follows the longer side of the stream resolution (landscape with the on-screen controls; tablets and other squarish screens may turn freely). The choice is kept for later streams.',
     '자동은 스트림 해상도의 긴 쪽에 맞춥니다(화면 컨트롤러를 쓰면 가로, 태블릿처럼 정사각형에 가까운 화면은 자유 회전). 고른 방향은 다음 스트림에도 유지됩니다.'),

    # Mouse tuning
    ('title_hermit_trackpad_speed', 'Trackpad speed', '트랙패드 감도'),
    ('summary_hermit_trackpad_speed', 'How far the pointer moves for a finger movement in trackpad mode', '트랙패드 모드에서 손가락 이동에 비해 커서가 움직이는 정도'),
    ('title_hermit_scroll_speed', 'Scroll speed', '스크롤 속도'),
    ('summary_hermit_scroll_speed', 'How fast dragging to scroll (one or two fingers) scrolls on the host',
     '손가락으로 끌어 스크롤할 때(한 손가락·두 손가락) PC에서 스크롤되는 속도'),

    # Device status in the overlay
    ('hermit_pc_searching_title', 'Looking for host PCs on your network', '로컬 네트워크에서 호스트 PC를 찾는 중'),
    ('hermit_pc_searching_hint', 'Make sure the streaming host (such as Shell) is running on your PC. A PC on another network can be added with + at the top right.',
     'PC에서 스트리밍 호스트(Shell 등)가 실행 중인지 확인하세요. 다른 네트워크의 PC는 오른쪽 위 +로 주소를 추가할 수 있습니다.'),
    ('hermit_action_help', 'Help', '도움말'),
    ('hermit_action_settings', 'Settings', '설정'),
    ('hermit_action_add_pc', 'Add a PC', 'PC 추가'),
    ('hermit_metric_device', 'This device (battery, heat)', '이 기기 (배터리, 발열)'),
    ('hermit_overlay_device', 'This device', '이 기기'),
    ('hermit_device_charging', '(charging)', '(충전 중)'),
    ('hermit_device_heat_none', 'heat: normal', '발열 정상'),
    ('hermit_device_heat_light', 'heat: light', '발열 약간'),
    ('hermit_device_heat_moderate', 'heat: moderate', '발열 보통'),
    ('hermit_device_heat_severe', 'heat: severe', '발열 심함'),
    ('hermit_device_heat_critical', 'heat: critical', '발열 위험'),
    ('hermit_keypad_haptics', 'Vibrate on each press', '누를 때 진동'),

    # Pinch zoom
    ('title_checkbox_hermit_pinch_zoom', 'Pinch to zoom the picture', '두 손가락으로 화면 확대'),
    ('summary_checkbox_hermit_pinch_zoom', 'Spread two fingers to enlarge the stream on this device; while zoomed in, drag with two fingers to move around. The host\'s picture does not change.',
     '두 손가락을 벌려 이 기기에서 스트림 화면을 확대하고, 확대된 상태에서는 두 손가락으로 끌어 이동합니다. 호스트의 화면은 바뀌지 않습니다.'),
    ('hermit_zoom_tag', '%1$d%%  ✕', '%1$d%%  ✕'),

    # Virtual keypad
    ('hermit_panel_keypad', 'Virtual keypad', '가상 키패드'),
    ('hermit_panel_keypad_edit', 'Edit keypad…', '키패드 편집…'),
    ('title_hermit_keypad', 'Virtual keypad', '가상 키패드'),
    ('summary_hermit_keypad', 'A joystick or D-pad on the left and keys on the right that send keyboard keys. Turn it on and change the layout and every key here or from the stream panel.',
     '왼쪽 조이스틱(또는 십자패드)과 오른쪽 키로 키보드 입력을 보냅니다. 여기나 스트림 패널에서 켜고, 배치와 모든 키를 바꿀 수 있습니다.'),
    ('hermit_keypad_title', 'Virtual keypad', '가상 키패드'),
    ('hermit_keypad_enable', 'Show the virtual keypad', '가상 키패드 표시'),
    ('hermit_keypad_section_stick', 'LEFT: DIRECTION', '왼쪽: 방향'),
    ('hermit_keypad_stick_mode', 'Type', '방식'),
    ('hermit_keypad_stick_fixed', 'Fixed joystick', '고정 조이스틱'),
    ('hermit_keypad_stick_floating', 'Floating joystick', '유동 조이스틱'),
    ('hermit_keypad_stick_dpad', 'D-pad', '십자패드'),
    ('hermit_keypad_eight_way', 'Diagonals (8 directions)', '대각선 입력 (8방향)'),
    ('hermit_keypad_stick_size', 'Size', '크기'),
    ('hermit_keypad_dir_up', 'Up', '위'),
    ('hermit_keypad_dir_down', 'Down', '아래'),
    ('hermit_keypad_dir_left', 'Left', '왼쪽'),
    ('hermit_keypad_dir_right', 'Right', '오른쪽'),
    ('hermit_keypad_section_keys', 'RIGHT: KEYS', '오른쪽: 키'),
    ('hermit_keypad_rows', 'Rows', '줄 수'),
    ('hermit_keypad_columns', 'Keys per row', '줄당 키 수'),
    ('hermit_keypad_stagger', 'Row offset', '줄 밀림'),
    ('hermit_keypad_key_size', 'Key size', '키 크기'),
    ('hermit_keypad_spacing', 'Spacing', '간격'),
    ('hermit_keypad_keys_hint', 'Tap a key to choose what it sends (keyboard key, mouse button, with Ctrl/Alt/Shift) and its label.',
     '키를 누르면 보낼 입력(키보드 키, 마우스 버튼, Ctrl/Alt/Shift 조합)과 표시 이름을 고를 수 있습니다.'),
    ('hermit_keypad_section_common', 'COMMON', '공통'),
    ('hermit_keypad_opacity', 'Opacity', '불투명도'),
    ('hermit_keypad_edit_positions', 'Move on screen', '화면에서 위치 조정'),
    ('hermit_keypad_edit_done', 'Drag the joystick and the keys, then tap here when done', '조이스틱과 키를 끌어 옮긴 뒤 여기를 눌러 완료'),
    ('hermit_keypad_reset', 'Defaults', '기본값으로'),
    ('hermit_keypad_reset_confirm', 'Reset the keypad to its defaults? Changed keys, sizes and positions will all be lost.',
     '키패드를 기본값으로 되돌릴까요? 바꾼 키, 크기, 위치가 모두 사라집니다.'),
    ('hermit_keypad_reset_do', 'Reset', '되돌리기'),
    ('hermit_keypad_preview_note', 'The keypad is off, so it shows only while you edit. To keep it, turn on Virtual keypad in the stream settings.',
     '키패드가 꺼져 있어 편집하는 동안만 보입니다. 계속 쓰려면 스트림 설정에서 가상 키패드를 켜세요.'),
    ('hermit_keypad_state_on', 'On', '켜짐'),
    ('hermit_keypad_state_off', 'Off', '꺼짐'),
    ('hermit_keypad_close', 'Close', '닫기'),
    ('hermit_keypad_done', 'Done', '완료'),
    ('hermit_keypad_collapse', 'Collapse', '접기'),
    ('hermit_keypad_expand', 'Expand', '펼치기'),
    ('hermit_keypad_live_hint', 'Drag the joystick and the keys on the screen; they snap to the grid. Changes show at once.',
     '조이스틱과 키를 화면에서 끌어 옮기세요. 격자에 맞춰 붙고, 바꾼 설정이 바로 보입니다.'),
    ('hermit_keypad_picker_title', '%1$s: choose a key', '%1$s: 보낼 키 선택'),
    ('hermit_keypad_key_title', 'Key %1$d-%2$d', '키 %1$d-%2$d'),
    ('hermit_keypad_combo', 'Combination: press several keys in order', '조합키: 여러 키를 순서대로 누르기'),
    ('hermit_keypad_combo_keys', '%1$s (%2$d of %3$d keys; tap a key again to take it out)', '%1$s (키 %2$d/%3$d개, 다시 누르면 빠짐)'),
    ('hermit_keypad_combo_delay', 'Delay between keys', '키 사이 간격'),
    ('hermit_keypad_combo_delay_hint', 'Ctrl, Alt, Shift and Win go down first, then the keys in order; they come up in reverse. Some games and programs need a delay to notice a combination.',
     'Ctrl·Alt·Shift·Win을 먼저 누르고 키를 순서대로 누른 뒤, 거꾸로 뗍니다. 일부 게임·프로그램은 간격이 있어야 조합을 인식합니다.'),
    ('hermit_keypad_quick_menu', 'Quick menu button', '빠른 메뉴 버튼'),
    ('hermit_keypad_quick_menu_hint', 'Touch mode, quality, screen orientation, text input and this editor in one tap. It sits above the keys until you drag it elsewhere.',
     '터치 방식, 화질, 화면 방향, 텍스트 입력, 이 편집기를 한 번에 엽니다. 다른 곳으로 끌어 옮기기 전까지 키 위에 붙어 있습니다.'),
    ('hermit_keypad_label_hint', 'Label on the button (optional)', '버튼에 표시할 이름 (선택)'),
    ('hermit_keypad_ok', 'OK', '확인'),
    ('hermit_keypad_cancel', 'Cancel', '취소'),
    ('hermit_keypad_mouse_left', 'L click', '좌클릭'),
    ('hermit_keypad_mouse_right', 'R click', '우클릭'),
    ('hermit_keypad_mouse_middle', 'Wheel', '휠클릭'),
    ('hermit_keypad_group_letters', 'Letters', '문자'),
    ('hermit_keypad_group_digits', 'Digits', '숫자'),
    ('hermit_keypad_group_arrows', 'Arrows', '방향키'),
    ('hermit_keypad_group_editing', 'Editing and special', '편집·특수'),
    ('hermit_keypad_group_modifiers', 'Modifiers', '조합 키'),
    ('hermit_keypad_group_function', 'Function keys', '기능 키'),
    ('hermit_keypad_group_symbols', 'Symbols', '기호'),
    ('hermit_keypad_group_numpad', 'Numpad', '숫자 키패드'),
    ('hermit_keypad_group_mouse', 'Mouse', '마우스'),

    # Bitrate dialog
    ('hermit_bitrate_recommended', 'Recommended for %1$dx%2$d at %3$d FPS: %4$d Mbps', '%1$dx%2$d · %3$d FPS 권장: %4$d Mbps'),
    ('hermit_bitrate_recommended_both', 'Recommended for %1$dx%2$d at %3$d FPS: %4$d Mbps (HEVC/AV1: %5$d Mbps)',
     '%1$dx%2$d · %3$d FPS 권장: %4$d Mbps (HEVC/AV1은 %5$d Mbps)'),

    # Clipboard sync
    ('title_checkbox_clipboard_sync', 'Sync clipboard with the host', '호스트와 클립보드 동기화'),
    ('summary_checkbox_clipboard_sync', 'What you copy on this device is sent to the host when you return to the stream, and what you copy on the host is brought back when you leave it. With a Shell host, images are synced too. Requires the clipboard permissions for this device on the host.',
     '스트림으로 돌아오면 이 기기에서 복사한 내용을 호스트로 보내고, 스트림에서 나가면 호스트에서 복사한 내용을 가져옵니다. Shell 호스트에서는 이미지도 동기화합니다. 호스트에서 이 기기에 클립보드 권한이 있어야 합니다.'),
    ('hermit_clipboard_sent_text', 'Clipboard text sent to the host', '클립보드 텍스트를 호스트로 보냈습니다'),
    ('hermit_clipboard_sent_image', 'Clipboard image sent to the host', '클립보드 이미지를 호스트로 보냈습니다'),
    ('hermit_clipboard_denied', 'The host does not allow clipboard sync for this device', '호스트가 이 기기의 클립보드 동기화를 허용하지 않습니다'),
    ('hermit_clipboard_too_large', 'The clipboard content is too large to send', '클립보드 내용이 너무 커서 보내지 못했습니다'),

    # Turning the host PC off or restarting it (PC list)
    ('hermit_power_menu_shutdown', 'Shut down PC…', 'PC 끄기…'),
    ('hermit_power_menu_restart', 'Restart PC…', 'PC 다시 시작…'),
    ('hermit_power_title', 'Shut down %1$s', '%1$s 끄기'),
    ('hermit_power_restart_title', 'Restart %1$s', '%1$s 다시 시작'),
    ('hermit_power_checking', 'Checking who is connected…', '접속 중인 기기를 확인하는 중…'),
    ('hermit_power_others', '%1$d other device(s) connected to this PC right now', '지금 이 PC에 다른 기기 %1$d대가 접속해 있습니다'),
    ('hermit_power_others_end', 'Their streams end when the PC turns off.', 'PC가 꺼지면 이 기기들의 스트림이 끊깁니다.'),
    ('hermit_power_others_end_restart', 'Their streams end when the PC restarts.', 'PC가 다시 시작하면 이 기기들의 스트림이 끊깁니다.'),
    ('hermit_power_confirm', 'Turn %1$s off? Apps on it are asked to close first.', '%1$s을(를) 끌까요? 실행 중인 앱에는 먼저 종료를 요청합니다.'),
    ('hermit_power_confirm_restart', 'Restart %1$s? Apps on it are asked to close first.', '%1$s을(를) 다시 시작할까요? 실행 중인 앱에는 먼저 종료를 요청합니다.'),
    ('hermit_power_force', 'Also close apps with unsaved work (it is lost)', '저장하지 않은 작업이 있는 앱도 닫기 (작업은 사라집니다)'),
    ('hermit_power_shutdown', 'Shut down', '끄기'),
    ('hermit_power_shutdown_anyway', 'Shut down anyway', '그래도 끄기'),
    ('hermit_power_restart', 'Restart', '다시 시작'),
    ('hermit_power_restart_anyway', 'Restart anyway', '그래도 다시 시작'),
    ('hermit_power_sending', 'Turning the PC off…', 'PC를 끄는 중…'),
    ('hermit_power_restarting', 'Restarting the PC…', 'PC를 다시 시작하는 중…'),
    ('hermit_power_sent', '%1$s turns off in a few seconds.', '%1$s이(가) 몇 초 뒤 꺼집니다.'),
    ('hermit_power_restart_sent', '%1$s restarts in a few seconds. It shows as online again once it has started.', '%1$s이(가) 몇 초 뒤 다시 시작합니다. 부팅이 끝나면 다시 온라인으로 표시됩니다.'),
    ('hermit_power_no_permission', 'This device may not turn the PC off or restart it. In the Shell web UI, open Pairing and allow this device to launch apps.',
     '이 기기에는 PC를 끄거나 다시 시작할 권한이 없습니다. Shell 웹 UI의 페어링 페이지에서 이 기기에 앱 실행 권한을 주세요.'),
    ('hermit_power_unsupported', "This host can't be turned off or restarted remotely. Update Shell on the host PC.", '이 호스트는 원격으로 끄거나 다시 시작할 수 없습니다. 호스트 PC의 Shell을 업데이트하세요.'),
    ('hermit_power_network', "Couldn't reach the host. Check the network and the PC.", '호스트에 연결하지 못했습니다. 네트워크와 PC 상태를 확인하세요.'),
    ('hermit_power_close', 'Close', '닫기'),
    ('hermit_power_failed', 'The host could not do it (error %1$d). Try again in a moment.', '호스트가 요청을 처리하지 못했습니다 (오류 %1$d). 잠시 후 다시 시도하세요.'),

    # Crash report
    ('hermit_crash_title', 'Hermit closed unexpectedly', 'Hermit이 비정상 종료되었습니다'),
    ('hermit_crash_message', 'The error details from the last run were saved. Copy or share them to find the cause.', '지난 실행의 오류 내용을 저장해 두었습니다. 원인을 확인하려면 복사하거나 공유하세요.'),
    ('hermit_crash_copy', 'Copy', '복사'),
    ('hermit_crash_share', 'Share', '공유'),
    ('hermit_crash_close', 'Close', '닫기'),
    ('hermit_crash_copied', 'Error details copied', '오류 내용을 복사했습니다'),

    # Auto-reconnect
    ('title_checkbox_auto_reconnect', 'Reconnect automatically when the connection drops', '연결이 끊기면 자동으로 다시 연결'),
    ('summary_checkbox_auto_reconnect', 'After a network drop, reconnects up to 3 times (5 seconds apart). Not used when no video ever arrived (firewall or port forwarding) or when the host refused the stream.',
     '네트워크 문제로 끊기면 5초 간격으로 최대 3번 다시 연결합니다. 영상이 한 번도 오지 않은 경우(방화벽·포트포워딩 문제)나 호스트가 거절한 경우에는 다시 시도하지 않습니다.'),
    ('hermit_reconnect_title', 'Connection lost', '연결 끊김'),
    ('hermit_reconnect_countdown', 'The connection was lost. Reconnecting in %1$d s.', '연결이 끊겼습니다. %1$d초 후 다시 연결합니다.'),
    ('hermit_reconnect_attempt', 'Attempt %1$d of %2$d', '시도 %1$d/%2$d'),
    ('hermit_reconnect_now', 'Connect now', '지금 연결'),
    ('hermit_reconnect_cancel', 'Cancel', '취소'),

    # Session summary
    ('title_checkbox_session_summary', 'Show a summary after each session', '세션이 끝나면 요약 보기'),
    ('summary_checkbox_session_summary', 'After a stream of at least 30 seconds, shows frame rate, network loss and latency compared with your previous sessions.',
     '30초 이상 스트리밍한 뒤 프레임 레이트, 네트워크 손실, 지연을 이전 세션들과 비교해 보여줍니다.'),
    ('hermit_summary_title', 'Session summary', '세션 요약'),
    ('hermit_summary_host', 'Host', '호스트'),
    ('hermit_summary_app', 'App', '앱'),
    ('hermit_summary_duration', 'Duration', '시간'),
    ('hermit_summary_video', 'Video', '영상'),
    ('hermit_summary_metric', 'Metric', '지표'),
    ('hermit_summary_this', 'This session', '이번 세션'),
    ('hermit_summary_previous', 'Previous 10 avg.', '지난 10회 평균'),
    ('hermit_summary_status', 'Status', '상태'),
    ('hermit_summary_avg_fps', 'Average FPS', '평균 FPS'),
    ('hermit_summary_bitrate', 'Bitrate', '비트레이트'),
    ('hermit_summary_bitrate_value', 'Average %1$s Mbps (set %2$s Mbps)', '평균 %1$s Mbps (설정 %2$s Mbps)'),
    ('hermit_summary_bitrate_avg', 'Average %1$s Mbps', '평균 %1$s Mbps'),
    ('hermit_summary_network_loss', 'Network loss', '네트워크 손실'),
    ('hermit_summary_host_avg', 'Host latency, average', '호스트 지연 (평균)'),
    ('hermit_summary_host_max', 'Host latency, maximum', '호스트 지연 (최대)'),
    ('hermit_summary_rtt', 'Round trip (RTT)', '왕복 지연 (RTT)'),
    ('hermit_summary_decode', 'Decode time', '디코드 시간'),
    ('hermit_summary_good', 'Good', '양호'),
    ('hermit_summary_check', 'Check', '주의'),
    ('hermit_summary_poor', 'Poor', '나쁨'),
    ('hermit_summary_minutes', '%1$d min', '%1$d분'),
    ('hermit_summary_hours', '%1$d h %2$d min', '%1$d시간 %2$d분'),
    ('hermit_summary_fps_note', 'The host sends frames only when the screen changes, so the average FPS is lower on quiet screens. Judge smoothness by network loss.',
     '호스트는 화면이 바뀔 때만 프레임을 보내므로 화면 변화가 적으면 평균 FPS가 낮게 나옵니다. 끊김은 네트워크 손실로 판단하세요.'),
    ('hermit_summary_loss_note', 'Many frames were lost on the network. Try a lower bitrate or a stronger Wi-Fi connection.',
     '네트워크에서 잃은 프레임이 많습니다. 비트레이트를 낮추거나 더 안정적인 Wi-Fi를 써 보세요.'),
    ('hermit_summary_close', 'Close', '닫기'),
    ('hermit_summary_dont_show', 'Don\'t show again', '다시 보지 않기'),

    # Performance overlay
    ('title_hermit_overlay_metrics', 'Performance overlay: metrics to show', '성능 오버레이: 표시할 지표'),
    ('summary_hermit_overlay_metrics', 'Choose the rows of the performance overlay', '성능 오버레이에 표시할 항목을 고릅니다'),
    ('title_hermit_overlay_text_size', 'Performance overlay: text size', '성능 오버레이: 글자 크기'),
    ('hermit_overlay_size_small', 'Small', '작게'),
    ('hermit_overlay_size_medium', 'Medium', '보통'),
    ('hermit_overlay_size_large', 'Large', '크게'),
    ('hermit_metric_video', 'Video (resolution, FPS, codec)', '영상 (해상도, FPS, 코덱)'),
    ('hermit_metric_frame_rates', 'Received / rendered FPS', '수신 / 렌더 FPS'),
    ('hermit_metric_bitrate', 'Bitrate', '비트레이트'),
    ('hermit_metric_network_loss', 'Network loss', '네트워크 손실'),
    ('hermit_metric_rtt', 'Round trip time', '왕복 지연'),
    ('hermit_metric_host_latency', 'Host latency', '호스트 지연'),
    ('hermit_metric_decode', 'Decode time', '디코드 시간'),
    ('hermit_metric_total_latency', 'Estimated total latency', '추정 전체 지연'),
    ('hermit_metric_decoder', 'Decoder', '디코더'),
    ('hermit_overlay_video', 'Video', '영상'),
    ('hermit_overlay_frame_rates', 'Received / rendered', '수신 / 렌더 FPS'),
    ('hermit_overlay_bitrate', 'Bitrate', '비트레이트'),
    ('hermit_overlay_network_loss', 'Network loss', '네트워크 손실'),
    ('hermit_overlay_rtt', 'Round trip', '왕복 지연'),
    ('hermit_overlay_host_latency', 'Host latency', '호스트 지연'),
    ('hermit_overlay_decode', 'Decode', '디코드'),
    ('hermit_overlay_total_latency', 'Estimated total latency', '추정 전체 지연'),
    ('hermit_overlay_decoder', 'Decoder', '디코더'),
    ('hermit_overlay_bitrate_value', '%1$s Mbps (peak %2$s)', '%1$s Mbps (최대 %2$s)'),
]

write('main/res/values/hermit_strings.xml',
      res('Hermit strings (Korean in values-ko/hermit_strings.xml). Generated by hermit/make_hermit_strings.py; edit that script, not this file.',
          [(n, e) for n, e, k, *f in hermit]), crlf=True)
write('main/res/values-ko/hermit_strings.xml',
      res('Hermit strings, Korean. Generated by hermit/make_hermit_strings.py.', [(n, k) for n, e, k, *f in hermit]), crlf=True)
print('ok', len(over_en), len(over_ko), len(hermit))
